# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cFq1T0kjnvmo8ORE6pronknxpu0ujHYl
"""

from flask import Flask, render_template, request
import pandas as pd
import unicodedata

app = Flask(__name__)

indice = pd.read_excel("Autores Completo.xlsx")

def remove_accents(input_str):
    if not isinstance(input_str, str):
        return input_str

    processed_str = input_str.lower()
    processed_str = processed_str.replace('ñ', '__NY__')

    nfkd_form = unicodedata.normalize('NFD', processed_str)

    only_ascii = ''.join([c for c in nfkd_form if not unicodedata.combining(c)])

    only_ascii = only_ascii.replace('__NY__', 'ñ')

    return only_ascii

synonym_map = {
    'marketing': ['mercadotecnia'],
    'educacion': ['enseñanza', 'formacion'],
}

def normalize_keyword_with_synonyms(keyword, synonym_dict):
    normalized_keyword = remove_accents(keyword.strip().lower())

    for preferred_term, synonyms in synonym_dict.items():
        if normalized_keyword == preferred_term or normalized_keyword in synonyms:
            return preferred_term

    return normalized_keyword

def calculate_match_score(author_keywords_string, user_keywords_list):
    if pd.isna(author_keywords_string):
        return 0

    author_keywords = [
        normalize_keyword_with_synonyms(kw, synonym_map)
        for kw in author_keywords_string.split(';')
        if kw.strip()
    ]

    total_match_count = 0

    for user_kw in user_keywords_list:
        if user_kw in author_keywords:
            total_match_count += 1

    return total_match_count

@app.route("/", methods=["GET", "POST"])
def home():
    resultados = []

    if request.method == "POST":
        keywords = request.form["keywords"]

        user_keywords = [
            normalize_keyword_with_synonyms(kw, synonym_map)
            for kw in keywords.split(',')
            if kw.strip()
        ]

        indice["score"] = indice["Columna2"].apply(
            lambda x: calculate_match_score(x, user_keywords)
        )

        resultados = indice.sort_values(by="score", ascending=False).head(10)

        resultados = resultados.to_dict(orient="records")

    return render_template("index.html", resultados=resultados)

if __name__ == "__main__":
    app.run(debug=True)
